### ISSUE TITLE
Kotlin JVM

### ISSUE THREAD

**Issue by Legion2** [Breina/OpenRGB.jar#1]
Thought about using Kotlin instead of plain java? It has a much nicer syntax and is compatible with java. Also all the `lombok` is already built into kotlin: non nullable types, data classes, extension functions, good std lib, delegation, coroutines ...

**Comment by Breina** [comment]
Cool language. Fixed in: 4d8351be22f80ce5c291261fc79405ce5b5f8ba0

**Comment by Legion2** [comment]
Nice that you are using it. Some tips:
- if you want a nice `toString`, `equals` and `hashCode` method, make the class a `data class`
- Many java streams and collection operations are much simpler with kotlin, for example you don't need `.stream()` and `.collect`
- basically anything that required wrapper in java works without in kotlin, thanks to extension functions

Happy coding ;)

**Comment by Breina** [comment]
Yeah I still have much to learn, but I'm liking it.

I'll gradually upgrade. Thanks for the tips! :)
